//
//  HomeViewController.swift
//  Imaging
//
//  Created by Raymond Law on 7/7/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class
{
  func displayFetchEntries(viewModel: Home.FetchEntries.ViewModel)
  func displaySetIcon(viewModel: Home.SetIcon.ViewModel)
}

class HomeViewController: UITableViewController, HomeDisplayLogic, EntryCellDelegate
{
  var interactor: HomeBusinessLogic?
  var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = HomeInteractor()
    let presenter = HomePresenter()
    let router = HomeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchEntries()
  }
  
  // MARK: Table view
  
  override func numberOfSections(in tableView: UITableView) -> Int
  {
    return 1
  }
  
  override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
  {
    return displayedEntries.count
  }
  
  override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
  {
    let displayedEntry = displayedEntries[indexPath.row]
    var cell = tableView.dequeueReusableCell(withIdentifier: "EntryCell") as? EntryCell
    if cell == nil {
      cell = UITableViewCell(style: .default, reuseIdentifier: "EntryCell") as? EntryCell
    }
    cell!.displayedEntry = displayedEntry
    cell?.delegate = self
    return cell!
  }
  
  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
  {
    // TODO: Route to detail view
  }
  
  // MARK: Fetch entries
  
  var displayedEntries = [Home.DisplayedEntry]()
  
  func fetchEntries()
  {
    let request = Home.FetchEntries.Request()
    interactor?.fetchEntries(request: request)
  }
  
  func displayFetchEntries(viewModel: Home.FetchEntries.ViewModel)
  {
    displayedEntries = viewModel.displayedEntries
    tableView.reloadData()
  }
  
  // MARK: Set icon
  
  func entryCellButtonTapped(entryCell: EntryCell)
  {
    if let indexPath = tableView.indexPath(for: entryCell) {
      setIcon(at: indexPath)
    }
  }
  
  func setIcon(at indexPath: IndexPath)
  {
    let request = Home.SetIcon.Request(viewController: self, indexPath: indexPath)
    interactor?.setIcon(request: request)
  }
  
  func displaySetIcon(viewModel: Home.SetIcon.ViewModel)
  {
    displayedEntries[viewModel.indexPath.row] = viewModel.displayedEntry
    tableView.reloadRows(at: [viewModel.indexPath], with: .automatic)
  }
}
