//
//  HomeWorker.swift
//  Imaging
//
//  Created by Raymond Law on 7/7/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
  let entries: [Entry] = [
    Entry(text: "Acey Mac", icon: UIImage(named: "Acey Mac")!),
    Entry(text: "Braeburn", icon: UIImage(named: "Braeburn")!),
    Entry(text: "Cameo", icon: UIImage(named: "Cameo")!),
    Entry(text: "Cortland", icon: UIImage(named: "Cortland")!),
    Entry(text: "Crispin", icon: UIImage(named: "Crispin")!),
    Entry(text: "Empire", icon: UIImage(named: "Empire")!),
    Entry(text: "Fortune", icon: UIImage(named: "Fortune")!),
    Entry(text: "Fuji", icon: UIImage(named: "Fuji")!),
    Entry(text: "Gala", icon: UIImage(named: "Gala")!),
    Entry(text: "Ginger Gold", icon: UIImage(named: "Ginger Gold")!),
    Entry(text: "Golden Delicious", icon: UIImage(named: "Golden Delicious")!),
    Entry(text: "Honeycrisp", icon: UIImage(named: "Honeycrisp")!),
    Entry(text: "Idared", icon: UIImage(named: "Idared")!),
    Entry(text: "Jersey Mac", icon: UIImage(named: "Jersey Mac")!),
    Entry(text: "Jonagold", icon: UIImage(named: "Jonagold")!),
    Entry(text: "Jonamac", icon: UIImage(named: "Jonamac")!),
    Entry(text: "Macoun", icon: UIImage(named: "Macoun")!),
    Entry(text: "McIntosh", icon: UIImage(named: "McIntosh")!),
    Entry(text: "Paula Red", icon: UIImage(named: "Paula Red")!),
    Entry(text: "Red Delicious ", icon: UIImage(named: "Red Delicious")!),
    Entry(text: "Rome", icon: UIImage(named: "Rome")!),
    Entry(text: "RubyFrost", icon: UIImage(named: "RubyFrost")!),
    Entry(text: "SnapDragon", icon: UIImage(named: "SnapDragon")!),
    Entry(text: "Zestar", icon: UIImage(named: "Zestar")!)
  ]
  
  func fetchEntries(completionHandler: ([Entry]) -> Void)
  {
    completionHandler(entries)
  }
}
